
name: Software Platform Lab 
title: Software Platform Lab @ SNU
description: "This is a page for Software Platform lab at Seoul National University"

#URL
baseurl: ""
url: "https://chang-jin.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
nav:
  - name:           "Home"
    href:           "/"
  - name:           "People"
    href:           "/people"
  - name:           "Updates"
    href:           "/updates"
  - name:           "Research"
    href:           "/research"
  - name:           "Publications"
    href:           "/publications"

# Sass
sass:
  style:              compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /:title
